import type { Metadata } from "next";
import { LegalLayout, ToComplete } from "../legal-layout";

export const metadata: Metadata = { title: "Politique de confidentialité | YuMan", description: "Comment YuMan utilise et protège les données personnelles." };

export default function PrivacyPolicy() {
  return <LegalLayout title="Politique de confidentialité" intro="Cette page décrit les données utilisées pour faire fonctionner YuMan et les choix dont vous disposez.">
    <aside className="legal-draft">Document à compléter avant publication : durées de conservation hors suppression de compte, localisation des traitements, garanties de transfert et liste définitive des prestataires.</aside>
    <section><h2>1. Responsable du traitement</h2><p>Le responsable du traitement est <strong>Lenny GOMES</strong>, entrepreneur individuel (micro-entreprise), éditeur de YuMan. Vous pouvez le contacter à <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>. Adresse professionnelle : <ToComplete>à compléter</ToComplete>.</p></section>
    <section><h2>2. Données utilisées</h2><p>Selon votre utilisation du service, YuMan traite :</p><ul><li>les données de compte : adresse e-mail, pseudonyme, nom affiché, photo de profil facultative, mode de connexion et mot de passe sous forme d’empreinte sécurisée pour les comptes créés par e-mail ;</li><li>les contributions et interactions : questions, réponses, catégories, likes, meilleure réponse choisie, signalements, blocages et données nécessaires à la modération ;</li><li>les données de notification : notifications reçues, état de lecture, jeton de notification push et type d’appareil lorsque vous activez cette fonction ;</li><li>les données techniques nécessaires à la connexion et au fonctionnement du service, qui peuvent figurer dans les journaux des hébergeurs et prestataires.</li></ul><p>Les questions, réponses, pseudonymes et photos de profil publiés sont visibles par les autres utilisateurs du service.</p></section>
    <section><h2>3. Pourquoi ces données sont traitées</h2><dl><dt>Fournir le service et gérer le compte</dt><dd>Créer le compte, authentifier l’utilisateur, afficher le profil, publier les questions et réponses et gérer les interactions. Base juridique envisagée : exécution des conditions d’utilisation.</dd><dt>Protéger la communauté</dt><dd>Examiner les signalements, filtrer certains contenus et agir contre les abus. Base juridique envisagée : intérêt légitime de l’éditeur à sécuriser le service et ses utilisateurs.</dd><dt>Envoyer des notifications</dt><dd>Informer des réponses et interactions liées au compte. Les notifications push dépendent des réglages de l’appareil. Base juridique et modalités d’activation à confirmer avant publication.</dd><dt>Répondre aux demandes et obligations</dt><dd>Traiter les messages envoyés à l’adresse de contact et les demandes relatives aux données. Les bases juridiques et éventuelles obligations de conservation doivent être précisées selon chaque situation.</dd></dl></section>
    <section><h2>4. Prestataires et destinataires</h2><p>Les données sont accessibles à l’éditeur pour gérer le service et, selon la fonctionnalité utilisée, à ses prestataires techniques. Les informations confirmées sont <strong>Vercel</strong> pour le site web et <strong>Neon</strong> pour la base de données. Le code du service utilise également <strong>Cloudflare R2</strong> pour les photos de profil, <strong>Google</strong> pour la connexion Google, <strong>Expo</strong> pour les notifications push et <strong>OpenAI</strong> pour la vérification automatisée des textes publiés. Des signalements de modération peuvent aussi être transmis à un canal <strong>Telegram</strong> configuré par l’éditeur.</p><p>L’hébergement effectif de l’API, les autres prestataires éventuellement actifs et les pays où chacun traite les données doivent être confirmés. <ToComplete>Liste définitive, lieux de traitement et garanties des transferts hors EEE à compléter.</ToComplete></p></section>
    <section><h2>5. Conservation et suppression</h2><p>Les données du compte sont utilisées pendant la vie du compte. Une demande de suppression programme l’effacement du compte 30 jours plus tard ; une reconnexion avant l’échéance annule cette demande. Le fonctionnement actuel prévoit alors la suppression du compte, de ses questions et réponses et des données qui en dépendent dans la base. Les photos de profil associées sont supprimées du stockage lorsque leur suppression est techniquement nécessaire. Les jetons de notification push sont retirés dès la demande.</p><p>Les délais applicables aux journaux techniques, sauvegardes, demandes de contact et éventuelles conservations imposées par la loi restent à définir. <ToComplete>Durées ou critères précis à compléter avant publication.</ToComplete></p></section>
    <section><h2>6. Vos droits</h2><p>Vous pouvez demander l’accès à vos données, leur rectification ou leur effacement et, selon le traitement concerné, leur limitation, leur portabilité ou vous opposer à leur utilisation. Si un traitement repose sur votre consentement, vous pouvez le retirer. Écrivez à <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a> pour exercer ces droits. Une vérification d’identité peut être demandée si elle est nécessaire pour éviter qu’un tiers accède à vos données.</p><p>Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes" target="_blank" rel="noreferrer">CNIL</a>.</p></section>
    <section><h2>7. Cookies et traceurs du site</h2><p>Le site de demande de suppression n’intègre actuellement aucun outil de publicité ou de mesure d’audience dans son code. Les données techniques éventuellement enregistrées par l’hébergement du site restent à confirmer. Si des traceurs non nécessaires sont ajoutés, cette section et les choix proposés aux visiteurs devront être mis à jour avant leur activation.</p></section>
    <section><h2>8. Mise à jour</h2><p>Cette politique sera mise à jour lorsque les traitements ou prestataires évolueront. La version publiée sur cette page est celle applicable au moment de sa consultation.</p></section>
  </LegalLayout>;
}
