import type { Metadata } from "next";
import { LegalLayout } from "../legal-layout";

export const metadata: Metadata = { title: "Politique de confidentialité | YuMan", description: "Comment YuMan utilise et protège les données personnelles." };

export default function PrivacyPolicy() {
  return <LegalLayout title="Politique de confidentialité" intro="Cette page décrit les données utilisées pour faire fonctionner YuMan et les choix dont vous disposez.">
    <section><h2>1. Responsable du traitement</h2><p>Le responsable du traitement est <strong>Lenny GOMES</strong>, auto-entrepreneur (SIRET 938 832 987 00011), éditeur de YuMan. Vous pouvez le contacter à <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>.</p></section>
    <section><h2>2. Données utilisées</h2><p>Selon votre utilisation du service, YuMan traite :</p><ul><li>les données de compte : adresse e-mail, pseudonyme, nom affiché, photo de profil facultative, mode de connexion (e-mail, Google ou Apple) et mot de passe sous forme d’empreinte sécurisée pour les comptes créés par e-mail ;</li><li>les contributions et interactions : questions, réponses, catégories, likes, meilleure réponse choisie, signalements, blocages et données nécessaires à la modération ;</li><li>les données de notification : notifications reçues, état de lecture, jeton de notification push et type d’appareil lorsque vous activez cette fonction ;</li><li>les données d’achat, si vous achetez un boost de visibilité : identifiant de transaction, produit acheté, prix, devise, store utilisé et question boostée. YuMan ne reçoit jamais vos données bancaires : le paiement est entièrement traité par Apple ou Google ;</li><li>les données techniques nécessaires à la connexion et au fonctionnement du service (adresse IP, type d’appareil, horodatage), qui peuvent figurer dans les journaux des hébergeurs.</li></ul><p>Les questions, réponses, pseudonymes et photos de profil publiés sont visibles par les autres utilisateurs du service.</p></section>
    <section><h2>3. Pourquoi ces données sont traitées</h2><dl><dt>Fournir le service et gérer le compte</dt><dd>Créer le compte, authentifier l’utilisateur, afficher le profil, publier les questions et réponses et gérer les interactions. Base juridique : exécution des conditions d’utilisation.</dd><dt>Traiter les achats</dt><dd>Activer le boost acheté, gérer les remboursements et tenir la comptabilité. Base juridique : exécution du contrat et obligations légales comptables.</dd><dt>Protéger la communauté</dt><dd>Examiner les signalements, vérifier automatiquement les textes publiés et agir contre les abus. Base juridique : intérêt légitime de l’éditeur à sécuriser le service et ses utilisateurs.</dd><dt>Envoyer des notifications</dt><dd>Informer des réponses et interactions liées au compte. Base juridique : votre consentement, donné via l’autorisation de notifications de votre appareil et retirable à tout moment dans ses réglages.</dd><dt>Répondre aux demandes</dt><dd>Traiter les messages envoyés à l’adresse de contact et les demandes relatives aux données. Base juridique : intérêt légitime et, pour les demandes d’exercice de droits, obligation légale.</dd></dl></section>
    <section><h2>4. Prestataires et destinataires</h2><p>Les données sont accessibles à l’éditeur et, uniquement pour ce qui est nécessaire à leur mission, aux prestataires techniques suivants :</p><ul><li><strong>Vercel</strong> : hébergement du site web ;</li><li><strong>Railway</strong> : hébergement de l’API de l’application ;</li><li><strong>Neon</strong> : base de données ;</li><li><strong>Cloudflare (R2)</strong> : stockage des photos de profil ;</li><li><strong>Google</strong> et <strong>Apple</strong> : connexion avec un compte Google ou Apple, et paiement des achats dans l’application ;</li><li><strong>RevenueCat</strong> : gestion et validation des achats dans l’application ;</li><li><strong>Expo</strong> : envoi des notifications push ;</li><li><strong>OpenAI</strong> : vérification automatisée des textes publiés, pour détecter les contenus contraires aux règles ;</li><li><strong>Telegram</strong> : transmission à l’éditeur des alertes de modération et d’achat.</li></ul><p>Ces prestataires sont pour la plupart établis aux États-Unis, et la base de données y est hébergée. Ces transferts hors de l’Union européenne sont encadrés par le Data Privacy Framework UE–États-Unis lorsque le prestataire y adhère, et à défaut par les clauses contractuelles types adoptées par la Commission européenne. Aucune donnée n’est vendue ni utilisée à des fins publicitaires.</p></section>
    <section><h2>5. Conservation et suppression</h2><dl><dt>Compte et contributions</dt><dd>Pendant toute la vie du compte. Une demande de suppression programme l’effacement du compte 30 jours plus tard ; une reconnexion avant l’échéance annule cette demande. Le compte, ses questions, réponses et données associées sont alors supprimés, ainsi que sa photo de profil. Les jetons de notification push sont retirés dès la demande.</dd><dt>Signalements et modération</dt><dd>1 an après le traitement du signalement, puis supprimés, sauf procédure en cours.</dd><dt>Données d’achat</dt><dd>10 ans, durée de conservation des pièces comptables imposée par la loi. Elles ne sont plus rattachées à votre compte après sa suppression.</dd><dt>Demandes de contact</dt><dd>3 ans après le dernier échange.</dd><dt>Journaux techniques et sauvegardes</dt><dd>Conservés par les hébergeurs pour une durée limitée, au plus 1 an, puis effacés automatiquement.</dd></dl></section>
    <section><h2>6. Vos droits</h2><p>Vous pouvez demander l’accès à vos données, leur rectification ou leur effacement et, selon le traitement concerné, leur limitation, leur portabilité ou vous opposer à leur utilisation. Si un traitement repose sur votre consentement, vous pouvez le retirer. Écrivez à <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a> pour exercer ces droits ; une réponse vous sera apportée dans un délai d’un mois. Une vérification d’identité peut être demandée si elle est nécessaire pour éviter qu’un tiers accède à vos données. Vous pouvez aussi supprimer votre compte directement depuis l’application.</p><p>Vous pouvez également adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes" target="_blank" rel="noreferrer">CNIL</a>.</p></section>
    <section><h2>7. Cookies et traceurs</h2><p>Le site et l’application n’utilisent aucun outil de publicité ni de mesure d’audience. Seules les données techniques strictement nécessaires au fonctionnement et à la sécurité sont enregistrées par les hébergeurs. Si des traceurs non nécessaires étaient ajoutés, cette section serait mise à jour et votre consentement demandé avant leur activation.</p></section>
    <section><h2>8. Mise à jour</h2><p>Cette politique est mise à jour lorsque les traitements ou les prestataires évoluent. La version publiée sur cette page est celle applicable au moment de sa consultation.</p></section>
  </LegalLayout>;
}
