import type { Metadata } from "next";
import { LegalLayout } from "../legal-layout";

export const metadata: Metadata = { title: "Conditions générales d’utilisation | YuMan", description: "Règles d’utilisation du service YuMan." };

export default function Terms() {
  return <LegalLayout title="Conditions générales d’utilisation" intro="Ces conditions expliquent comment utiliser YuMan et participer aux échanges entre membres.">
    <aside className="legal-draft">Document à valider avant publication : âge minimum éventuel, règles de modération définitives et modalités d’information en cas de changement des conditions.</aside>
    <section><h2>1. Le service</h2><p>YuMan permet de publier des questions, d’y répondre et de consulter les échanges de la communauté. Les utilisateurs peuvent notamment choisir une catégorie, aimer des réponses, désigner une meilleure réponse pour leur question, signaler un contenu et bloquer un autre compte. Certaines fonctions nécessitent un compte.</p></section>
    <section><h2>2. Création et sécurité du compte</h2><p>Vous devez fournir des informations exactes lors de votre inscription et garder vos identifiants confidentiels. Un compte peut être créé avec une adresse e-mail et un mot de passe ou avec Google, lorsque cette option est disponible. Vous êtes responsable de l’utilisation de votre compte, sauf utilisation indépendante de votre volonté que vous nous signalez sans délai à <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>.</p></section>
    <section><h2>3. Contributions</h2><p>Vous êtes responsable des questions, réponses et images que vous publiez. Vous vous engagez à respecter les autres utilisateurs, la loi et les droits des tiers. Les contenus haineux, menaçants, harcelants, illégaux, trompeurs ou portant atteinte à la vie privée d’autrui ne sont pas autorisés. Ne publiez pas de données personnelles sensibles vous concernant ou concernant un tiers dans une question publique.</p><p>Vous conservez vos droits sur vos contributions. Vous autorisez YuMan à les afficher et à les rendre accessibles dans le service pendant leur mise en ligne, dans la mesure nécessaire à son fonctionnement. Vous pouvez demander la suppression de votre compte selon la procédure ci-dessous.</p></section>
    <section><h2>4. Modération et signalements</h2><p>YuMan peut soumettre les questions et réponses à une vérification automatisée et recevoir des signalements. L’éditeur peut examiner un contenu signalé et, si nécessaire, le retirer ou suspendre le compte concerné. Une vérification automatisée peut se tromper et ne remplace pas une analyse humaine lorsque celle-ci est nécessaire. Pour contester une décision ou signaler un problème, contactez <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>.</p></section>
    <section><h2>5. Informations échangées</h2><p>Les réponses sont fournies par les membres de la communauté. Elles reflètent leur expérience et ne constituent pas une garantie d’exactitude ni un conseil professionnel personnalisé, notamment en matière de santé, de droit ou de finances. En cas de besoin important, adressez-vous à un professionnel qualifié.</p></section>
    <section><h2>6. Disponibilité</h2><p>L’éditeur s’efforce de maintenir YuMan accessible et peut faire évoluer, interrompre temporairement ou retirer une fonctionnalité pour des raisons techniques, de sécurité ou de modération. Les incidents peuvent être signalés à l’adresse de contact ci-dessus.</p></section>
    <section><h2>7. Suppression du compte</h2><p>Vous pouvez demander la suppression depuis les paramètres de l’application ou depuis la <a href="/suppression-compte">page de suppression</a>. La suppression est programmée 30 jours après la demande. Une reconnexion pendant ce délai annule la demande. À l’issue du délai, le compte et les contenus associés sont supprimés selon le fonctionnement décrit dans la <a href="/politique-confidentialite">politique de confidentialité</a>.</p></section>
    <section><h2>8. Modification des conditions</h2><p>Ces conditions peuvent évoluer pour refléter les changements du service ou du cadre applicable. La version en vigueur est celle publiée sur cette page. Pour toute question sur leur application, contactez <a href="mailto:gleam-pro@proton.me">gleam-pro@proton.me</a>.</p></section>
  </LegalLayout>;
}
